"""Unit tests for Phase 5: Upgraded Local Intelligence & Model Router.

Verifies:
1. Task classification across all specialized categories.
2. Model routing to specialized roles (Fast, Reasoning, Document, Coding, Vision, Embeddings, Cloud).
3. Fallback resolution when a specialized model is missing.
4. RoutedLLMProvider dynamic dispatching and transparency.
5. ModelRouteInspectTool execution and ground-truth verification.
"""

from __future__ import annotations
import unittest
from typing import Any, Dict, List, Optional

from jarvis.core.llm_provider import LLMProvider, ModelRole
from jarvis.core.model_manager import ModelManager
from jarvis.core.router import ModelRouter, TaskType
from jarvis.subsystems.local.routed_provider import RoutedLLMProvider
from jarvis.tools import get_default_registry


class MockUnderlyingProvider(LLMProvider):
    """Mock provider recording which model and role received each call."""

    def __init__(self, available_models: Optional[List[str]] = None):
        self.available_models = available_models or [
            "qwen2.5:1.5b",
            "qwen2.5:3b",
            "qwen2.5-coder:1.5b",
            "llava",
            "nomic-embed-text",
        ]
        self.last_model_used: Optional[str] = None
        self.last_role_used: Optional[ModelRole] = None

    def list_models(self) -> List[str]:
        return self.available_models

    def generate(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        model: Optional[str] = None,
        role: Optional[ModelRole] = None,
        **kwargs,
    ) -> str:
        self.last_model_used = model
        self.last_role_used = role
        return f"[Generated by {model} (role: {role}) for: {prompt[:30]}]"

    def structured_output(
        self,
        prompt: str,
        schema: Dict[str, Any],
        system_prompt: Optional[str] = None,
        model: Optional[str] = None,
        role: Optional[ModelRole] = None,
        **kwargs,
    ) -> Dict[str, Any]:
        self.last_model_used = model
        self.last_role_used = role
        return {"result": f"Structured by {model}", "role": str(role)}

    def embed(
        self,
        text: str,
        model: Optional[str] = None,
        role: Optional[ModelRole] = None,
        **kwargs,
    ) -> List[float]:
        self.last_model_used = model
        self.last_role_used = role
        return [0.1, 0.2, 0.3]

    def vision(
        self,
        image_data: str,
        prompt: str,
        model: Optional[str] = None,
        role: Optional[ModelRole] = None,
        **kwargs,
    ) -> str:
        self.last_model_used = model
        self.last_role_used = role
        return f"[Vision analyzed by {model}]"


class TestModelRouter(unittest.TestCase):
    """Tests for the ModelRouter and task dispatch."""

    def setUp(self):
        self.manager = ModelManager()
        self.router = ModelRouter(model_manager=self.manager)
        self.mock_provider = MockUnderlyingProvider()
        self.routed_provider = RoutedLLMProvider(
            router=self.router,
            local_provider=self.mock_provider,
        )

    def test_simple_command_routing(self):
        """Verify simple commands route to small fast local model (qwen2.5:1.5b)."""
        prompt = "Open VS Code"
        decision = self.router.route(prompt)

        self.assertEqual(decision.task_type, TaskType.SIMPLE_COMMAND)
        self.assertEqual(decision.role, ModelRole.FAST)
        self.assertEqual(decision.model_name, "qwen2.5:1.5b")

        # Execute through RoutedLLMProvider
        res = self.routed_provider.generate(prompt)
        self.assertEqual(self.mock_provider.last_model_used, "qwen2.5:1.5b")
        self.assertEqual(self.mock_provider.last_role_used, ModelRole.FAST)
        self.assertIn("qwen2.5:1.5b", res)

    def test_planning_routing(self):
        """Verify planning prompts route to better reasoning model (qwen2.5:3b)."""
        prompt = "Plan step by step how to organize my downloads directory, detect duplicates, and sort files."
        decision = self.router.route(prompt)

        self.assertEqual(decision.task_type, TaskType.PLANNING)
        self.assertEqual(decision.role, ModelRole.REASONING)
        self.assertEqual(decision.model_name, "qwen2.5:3b")

        self.routed_provider.generate(prompt)
        self.assertEqual(self.mock_provider.last_model_used, "qwen2.5:3b")
        self.assertEqual(self.mock_provider.last_role_used, ModelRole.REASONING)

    def test_document_summary_routing(self):
        """Verify document summarization prompts route to local document LLM (qwen2.5:3b)."""
        prompt = "Summarize Lecture 3 and 4 PDF and extract key topics for my upcoming exam."
        decision = self.router.route(prompt)

        self.assertEqual(decision.task_type, TaskType.DOCUMENT_SUMMARY)
        self.assertEqual(decision.role, ModelRole.DOCUMENT)
        self.assertEqual(decision.model_name, "qwen2.5:3b")

        self.routed_provider.generate(prompt)
        self.assertEqual(self.mock_provider.last_model_used, "qwen2.5:3b")
        self.assertEqual(self.mock_provider.last_role_used, ModelRole.DOCUMENT)

    def test_coding_routing(self):
        """Verify coding prompts route to specialized coding model (qwen2.5-coder:1.5b)."""
        prompt = "Write a python function to compute fast Fourier transform using numpy and fix the syntax error."
        decision = self.router.route(prompt)

        self.assertEqual(decision.task_type, TaskType.CODING)
        self.assertEqual(decision.role, ModelRole.CODING)
        self.assertEqual(decision.model_name, "qwen2.5-coder:1.5b")

        self.routed_provider.generate(prompt)
        self.assertEqual(self.mock_provider.last_model_used, "qwen2.5-coder:1.5b")
        self.assertEqual(self.mock_provider.last_role_used, ModelRole.CODING)

    def test_vision_routing(self):
        """Verify vision queries route to multimodal vision model (llava)."""
        prompt = "Look at the screenshot and find the login button on the screen."
        decision = self.router.route(prompt)

        self.assertEqual(decision.task_type, TaskType.VISION)
        self.assertEqual(decision.role, ModelRole.VISION)
        self.assertEqual(decision.model_name, "llava")

        self.routed_provider.vision(image_data="base64_fake_data", prompt=prompt)
        self.assertEqual(self.mock_provider.last_model_used, "llava")
        self.assertEqual(self.mock_provider.last_role_used, ModelRole.VISION)

    def test_embedding_routing(self):
        """Verify embeddings route to dedicated embedding model (nomic-embed-text)."""
        vec = self.routed_provider.embed("Nyquist sampling theorem for digital communications")
        self.assertEqual(self.mock_provider.last_model_used, "nomic-embed-text")
        self.assertEqual(self.mock_provider.last_role_used, ModelRole.EMBEDDING)
        self.assertEqual(len(vec), 3)

    def test_cloud_model_routing(self):
        """Verify explicit cloud queries route to cloud model (gemini-1.5-flash)."""
        prompt = "Use cloud model Gemini to analyze high-dimensional tensor networks."
        decision = self.router.route(prompt)

        self.assertEqual(decision.task_type, TaskType.CLOUD_REASONING)
        self.assertEqual(decision.role, ModelRole.CLOUD)
        self.assertEqual(decision.model_name, "gemini-1.5-flash")
        self.assertEqual(decision.provider_type, "cloud")

    def test_graceful_fallback_when_model_missing(self):
        """Verify graceful fallback if a specialized model is missing in local Ollama."""
        # Simulate only qwen2.5:3b and qwen2.5:1.5b installed (no coder model)
        limited_models = ["qwen2.5:3b", "qwen2.5:1.5b"]
        router_with_limited = ModelRouter(model_manager=self.manager)

        coding_prompt = "def calculate_hash(data): pass. Debug this python function."
        decision = router_with_limited.route(
            coding_prompt, available_models=limited_models
        )

        # Should fall back to reasoning model (qwen2.5:3b)
        self.assertEqual(decision.role, ModelRole.CODING)
        self.assertIn(decision.model_name, limited_models)
        self.assertEqual(decision.model_name, "qwen2.5:3b")

    def test_model_route_inspect_tool(self):
        """Verify ModelRouteInspectTool in registry."""
        registry = get_default_registry()
        tool = registry.get("model_route_inspect")
        self.assertIsNotNone(tool)

        res = tool.execute({"prompt": "write a python script to parse logs"})
        self.assertTrue(res.success)
        self.assertEqual(res.output["role"], "CODING")

        ver = tool.verify({"prompt": "write a python script to parse logs"}, res)
        self.assertTrue(ver.verified)


if __name__ == "__main__":
    unittest.main()
